ci: upload car to filebase

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,7 +43,6 @@ jobs:
       - name: Merkelize Build
         id: merklize
         run: |
-          # Capture stderr to which the CID is printed. See https://github.com/storacha/ipfs-car/pull/169
           CID=$(npx ipfs-car pack out --no-wrap --output build.car 2>&1 | tail -n 1)
           echo "cid=$CID" >> "$GITHUB_OUTPUT"
           echo $CID
@@ -54,7 +53,7 @@ jobs:
           name: build-output-car
           path: build.car
 
-  publish-to-ipfs:
+  upload-car-to-storacha:
     runs-on: 'ubuntu-latest'
     needs: 'build'
     if: success() && (github.event_name == 'push' || github.event_name == 'pull_request')
@@ -62,7 +61,7 @@ jobs:
       - name: Check required secrets
         run: |
           if [ -z "${{ secrets.STORACHA_KEY }}" ] || [ -z "${{ secrets.STORACHA_PROOF }}" ]; then
-            echo "::error::Missing required secrets STORACHA_KEY and/or STORACHA_PROOF"
+            echo "::error::Missing required secrets STORACHA_KEY and STORACHA_PROOF"
             exit 1
           fi
 
@@ -91,6 +90,35 @@ jobs:
             exit 1
           fi
 
+  upload-car-to-filebase:
+    runs-on: 'ubuntu-latest'
+    needs: 'build'
+    if: success() && (github.event_name == 'push' || github.event_name == 'pull_request')
+    steps:
+      - name: Download build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: build-output-car
+
+      - name: Check required secrets
+        run: |
+          if [ -z "${{ secrets.FILEBASE_SECRET_KEY }}" ] || [ -z "${{ secrets.FILEBASE_ACCESS_KEY }}" ]; then
+            echo "::error::Missing required secrets FILEBASE_SECRET_KEY and FILEBASE_ACCESS_KEY"
+            exit 1
+          fi
+
+      - name: Upload CAR to Filebase
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.FILEBASE_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.FILEBASE_SECRET_KEY }}
+          FILEBASE_BUCKET: ${{ secrets.FILEBASE_BUCKET }}
+        run: |
+          aws --endpoint https://s3.filebase.com s3 cp build.car s3://${FILEBASE_BUCKET} --debug --metadata 'import=car'
+
+  update-commit-status:
+    runs-on: 'ubuntu-latest'
+    needs: ['build', 'upload-car-to-storacha', 'upload-car-to-filebase']
+    steps:
       - name: Update commit status
         uses: actions/github-script@v7
         with:
